### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by JessePeplinski** [hackpotsdam/hackpotsdam2017#29]
- [x] Contact Information
- [x] Useful links (all external pages)
- [x] Connect with Potsdam's ACM
- [x] Connect with Clarkson's COSI

_Copied from original issue: PotsdamACM/hackpotsdam#6_

**Comment by lannonbr** [comment]
Here is the links for COSI:

Homepage: http://cosi.clarkson.edu/cosi.html
Mailing List: http://lists.clarkson.edu/mailman/listinfo/cslabannounce
Github: https://github.com/COSI-Lab/
