### ISSUE TITLE
Photos on where to park and where to go

### ISSUE THREAD

**Issue by JessePeplinski** [hackpotsdam/hackpotsdam2017#36]
One of the biggest fears of hackathons is not knowing where to go. If we took a quick video, sped it up, and put some happy music over it I think that people would feel more comfortable to go.

**Comment by JessePeplinski** [comment]
@lannonbr - Would you mind taking some pictures of parking and the venue and posting them to the FAQ page? Also see the comment and let me know your thoughts!

**Comment by lannonbr** [comment]
I got the aerial map of Clarkson and I am highlighting the buildings where COSI and the MPRs are, as well as the parking lot in front of them. I likely will talk to Campus Safety to make sure people can park there over the weekend, but I won't worry about that until next semester.
![hack_potsdam_map](https://cloud.githubusercontent.com/assets/3685876/20229275/81641b32-a823-11e6-9f50-cae14490f0a1.jpeg)

I can also list the room numbers for both the MPRs and COSI in the FAQ.

Does this look good?

**Comment by JessePeplinski** [comment]
Looks great Ben! I'll upload it later. Thanks!

**Comment by JessePeplinski** [comment]
Hey Ben, I pushed the image. Can you let me know the room numbers for MPR and COSI?

**Comment by lannonbr** [comment]
241-243 in the student center for the MPRs and Science center 334/336 for the labs

**Comment by JessePeplinski** [comment]
Updated. Thanks Ben!
